---
# file: common.yml
- hosts: iontorrent_master:iontorrent_computes
  roles:
    - common
  tags:
    - common
  vars_files:
    - [ "group_vars/all_local", "group_vars/all" ]
    - [ "group_vars/torrent_suite_version_local", "/etc/torrent_suite_version"]
